var rule = {
    title: '糖果影院',
    host: 'http://www.6tg.net/',
    url: '/html/fyclass/index_fypage.html[/html/fyclass/index.html]', //http://www.6tg.net/html/6/index.htmlhttp://www.6tg.net/html/6/index_3.html
    searchUrl: '/playsearch/-------------/?wd=**',
    searchable: 2,
    quickSearch: 0,
    filterable: 0,
    headers: {
        'User-Agent': 'UC_UA',
    },
    class_name: '动作片&喜剧片&爱情片&科幻片&恐怖片&剧情片&战争片&记录片&国产剧&港台剧&日韩剧&欧美剧&海外剧&综艺&动漫&短剧',
    class_url: '6&7&8&9&10&11&12&20&13&14&15&16&23&3&4&26',
    // class_parse: '.stui-header__menu li:gt(0):lt(7);a&&Text;a&&href;/(\\d+)',
    play_parse: true,
    lazy: "js:  let html = request(input);  let hconf = html.match(/r player_.*?=(.*?)</)[1];  let json = JSON5.parse(hconf);  let url = json.url;  if (json.encrypt == '1') {    url = unescape(url);  } else if (json.encrypt == '2') {    url = unescape(base64Decode(url));  }  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {    input = {      parse: 0,      jx: 0,      url: url,    };  } else {    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;  }",
    limit: 6,
    double: true,
    推荐: 'ul.stui-vodlist.clearfix;li;a&&title;.lazyload&&data-original;.pic-text&&Text;a&&href',
    一级: '.stui-vodlist li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
    二级: {
        title: '.stui-content__detail .title&&Text;.stui-content__detail&&p:eq(-2)&&a&&Text',
        title1: '.stui-content__detail .title&&Text;.stui-content__detail&&p&&Text',
        img: '.stui-content__thumb .lazyload&&data-original',
        desc: '.stui-content__detail p&&Text;.stui-content__detail&&p:eq&&a:eq(7)&&Text;.stui-content__detail&&p:eq&&a:eq(6)&&Text;.stui-content__detail p:eq(2)&&Text;.stui-content__detail p:eq(1)&&Text',
        desc1: '.stui-content__detail p:eq(4)&&Text;;;.stui-content__detail p:eq(1)&&Text',
        content: '.desc.hidden-xs&&Text',
        tabs: '.stui-pannel__head h3',
        tabs1: '.stui-vodlist__head h3',
        lists: '.stui-content__playlist:eq(#id) li',
    },
    搜索: 'ul.stui-vodlist__media,ul.stui-vodlist,#searchList li;a&&title;.lazyload&&data-original;.pic-text&&Text;a&&href;.detail&&Text',
}